# Generated by Django 5.0.4 on 2024-04-08 23:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('property_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Apartment',
            fields=[
                ('property', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='property_app.property')),
                ('bedroom', models.IntegerField()),
                ('bathroom', models.IntegerField()),
            ],
        ),
    ]
