apiVersion: v1
kind: Service
metadata:
  name: backend-service
  namespace: inhome-namespace
spec:
  selector:
    app: backend
  ports:
    - protocol: TCP
      port: 8000
      targetPort: 8000
      # nodePort: 30008 # This is the port that will be exposed to the outside
  # type: NodePort
  type: ClusterIP