apiVersion: v1
kind: ConfigMap
metadata:
  name: nginx-config
  namespace: inhome-namespace
data:
  default.conf: |
    server {
        listen 80;
        server_name localhost; 

        location /api/v1/ {
            proxy_pass http://backend-service.inhome-namespace.svc.cluster.local:8000/api/v1/;
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
            proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
            proxy_set_header X-Forwarded-Proto $scheme;
        }

        location / {
            root /usr/share/nginx/html;
            index index.html index.htm;
            try_files $uri $uri/ /index.html;
        }
    }
