apiVersion: v1
kind: Secret
metadata:
  name: inhome-secrets
  namespace: inhome-namespace
type: Opaque
data:
  POSTGRES_USER: aW5ob21l # base64-encoded "inhome"
  POSTGRES_PASSWORD: cGFzc3dvcmQ= # base64-encoded "password"
  POSTGRES_DB: aW5ob21lZGI= # base64-encoded "inhomedb"
  DJANGO_KEY: ZGphbmdvLWluc2VjdXJlLWUpaC1fJThlOWshZ143ZXV2bHBfenJ1eHUrKSRtNSk4eXg0KTAoXyN1eSRzKzRhMW9s # base64-encoded 'django-insecure-e)h-_%8e9k!g^7euvlp_zruxu+)$m5)8yx4)0(_#uy$s+4a1ol'
  API_AUTH_ID: WXpaa09UY3pabVV0WkRjeVpDMDJZVE5pTFRabFptWXRaakkzTW1JME5XUXpaV015
  API_AUTH_TOKEN: UXQ4NkVSaTJDNEZCb2tpNXBXbFI=
  API_KEY: YmRjXzliODU3Y2YyNWE2YTRhYjdiMWM1YmMwZmU0MDY0NDk4
  BACKEND_SERVICE_HOST: YmFja2VuZC1zZXJ2aWNlLmluaG9tZS1uYW1lc3BhY2Uuc3ZjLmNsdXN0ZXIubG9jYWw= # base64-encoded "backend-service.inhome-namespace.svc.cluster.local"
  BACKEND_SERVICE_PORT: ODAwMA== # base64-encoded "8000"