# Generated by Django 5.0.4 on 2024-04-08 23:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Property',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('street', models.CharField()),
                ('apt', models.CharField()),
                ('city', models.CharField()),
                ('state', models.CharField()),
                ('zip', models.CharField()),
                ('vacant', models.BooleanField(default=True)),
            ],
        ),
    ]
