name: Full Stack CI/CD

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  # Job 1: Backend
  backend-test:
    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres:13
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgres
          POSTGRES_DB: mydb
        ports:
          - 5432:5432
        options: >-
          --health-cmd "pg_isready -U postgres"
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    steps:
      # Step 1: Check out the repository
      - name: Checkout repository
        uses: actions/checkout@v3

      # Step 2: Set up Python environment
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'

      # Step 3: Install backend dependencies
      - name: Install Python dependencies
        run: |
          cd backend
          python -m venv venv
          source venv/bin/activate
          pip install -r requirements.txt

  # Job 2: Frontend - Vite Build
  frontend-build:
    runs-on: ubuntu-latest
    needs: backend-test  # Only run if backend-test succeeds

    steps:
      # Step 1: Check out the repository
      - name: Checkout repository
        uses: actions/checkout@v3

      # Step 2: Set up Node.js environment
      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      # Step 3: Install frontend dependencies
      - name: Install frontend dependencies
        run: |
          cd frontend
          npm install

      # Step 5: Build frontend
      - name: Build frontend
        run: |
          cd frontend
          npm run build

  # Job 3: Deployment (Optional)
  # deploy:
  #   runs-on: ubuntu-latest
  #   needs: [backend-test, frontend-build]  # Only run if both jobs succeed
  #   if: github.ref == 'refs/heads/main' && github.event_name == 'push'

  #   steps:
  #     # Step 1: Configure AWS Credentials
  #     - name: Configure AWS credentials
  #       uses: aws-actions/configure-aws-credentials@v2
  #       with:
  #         aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
  #         aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
  #         aws-region: us-east-1  # Change this to your region

  #     # Step 2: Deploy Backend (e.g., EC2, ECS, Lambda)
  #     - name: Deploy backend to EC2
  #       run: |
  #         # Add your deployment commands here, for example, SSH into EC2 and deploy the backend
  #         echo "Deploying Python backend to EC2..."

  #     # Step 3: Deploy Frontend (e.g., S3, CloudFront)
  #     - name: Deploy frontend to S3
  #       run: |
  #         aws s3 sync ./frontend/dist s3://your-s3-bucket-name --delete
  #         echo "Deployed Vite frontend to S3"
